obstacle_range: 2.0
raytrace_range: 2.5
#footprint: [[0.15, 0.24], [0.15, -0.24], [-0.39, -0.24], [-0.39, 0.24]]
footprint: [[0.12, 0.0], [0.065, 0.12], [-0.3, 0.12], [-0.3, -0.12], [0.065, -0.12]]

#footprint_inflation: 0.01
#robot_radius: 0.175

#inflation_radius: 0.25
inflation_radius: 0.1

cost_scaling_factor: 1.0
#imax_obstacle_height: 0.6
#min_obstacle_height: 0.0
#observation_sources: scan
#scan: {data_type: LaserScan, topic: /xv11_scan, marking: true, clearing: true, expected_update_rate: 0}
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: xv11, data_type: LaserScan, topic: /xv11_scan, marking: true, clearing: true, expected_update_rate: 0.4}
